### ISSUE TITLE
fail when trying to install trilinos

### ISSUE THREAD

**Issue by bnwind** [brewsci/homebrew-science#13]
```
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/superlu_dist/5.1.0
==> make
==> make install
==> make test
Last 15 lines from /Users/ning/Library/Logs/Homebrew/superlu_dist/04.make:
Test project /tmp/superlu_dist-20180116-66311-3vvpm4/SuperLU_DIST_5.1.0/build
    Start 1: pddrive
1/2 Test #1: pddrive ..........................***Failed    0.13 sec
    Start 2: pddrive1
2/2 Test #2: pddrive1 .........................***Failed    0.05 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.19 sec

The following tests FAILED:
	  1 - pddrive (Failed)
	  2 - pddrive1 (Failed)
Errors while running CTest
make: *** [test] Error 8
```

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

# Hosting Your Own Tap

Anyone can host their own tap. See [Interesting Taps & Forks](https://docs.brew.sh/Interesting-Taps-and-Forks.html) and [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html)

**Comment by sjackman** [comment]
This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core.
