### ISSUE TITLE
vigra build failed.

### ISSUE THREAD

**Issue by myso-kr** [brewsci/homebrew-science#15]
This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

# Hosting Your Own Tap

Anyone can host their own tap. See [Interesting Taps & Forks](https://docs.brew.sh/Interesting-Taps-and-Forks.html) and [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html)

Brew Log
https://gist.github.com/1d6e6a7c8e7b7138f04dcfe60ada92bc

**Comment by sjackman** [comment]
```
/tmp/vigra-20180121-6328-1mnulfa/vigra-1.11.1/test/multiconvolution/test.cxx:371:13: error: no matching function for call to 'symmetricGradientMultiArray'
```
https://gist.github.com/anonymous/1d6e6a7c8e7b7138f04dcfe60ada92bc#file-03-make-L973

**Comment by myso-kr** [comment]
thx. i found temporary solution.
`brew install --without-check vigra`

from
https://github.com/Homebrew/homebrew-science/issues/2428#issuecomment-116437884

**Comment by sjackman** [comment]
Glad to hear that you got it working.
`vigra` is up for migration to Homebrew/core. Consider submitting this formula to https://github.com/Homebrew/homebrew-core. This repository Homebrew/science is retired.
