### ISSUE TITLE
cannot install mumps on mac

### ISSUE THREAD

**Issue by yufeiliubrown** [brewsci/homebrew-science#166]
I am trying to install ipopt by running: _brew install ipopt.rb --with-openblas_ and got this error:

==> Installing dependencies for ipopt: mumps
==> Installing ipopt dependency: mumps
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz
Already downloaded: /Users/yufeiliu/Library/Caches/Homebrew/mumps-5.1.1.tar.gz
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.
Last 15 lines from /Users/yufeiliu/Library/Logs/Homebrew/mumps/01.make:
clang -fPIC -I../include -O  -c symbfac.c -o symbfac.o
clang -fPIC -I../include -O  -c interface.c -o interface.o
clang -fPIC -I../include -O  -c sort.c -o sort.o
clang -fPIC -I../include -O  -c minpriority.c -o minpriority.o
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o 
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

Does anyone know how to resolve this?

**Comment by yufeiliubrown** [comment]
Running _brew gist-logs mumps_ I got the result here: https://gist.github.com/yufeiliubrown/bf6ea0bd065a521398b80622458c2f97

**Comment by sjackman** [comment]
See https://github.com/dpo/homebrew-openblas/blob/master/mumps.rb
```sh
brew install dpo/openblas/mumps
```
@dpo Any thoughts on moving `dpo/openblas` to `brewsci/numeric` (or whichever name) ?
We have `brewsci/base` now, so you could be repo number three! =)

**Comment by yufeiliubrown** [comment]
The problem is solved. Thanks a lot!

**Comment by sjackman** [comment]
Glad to hear it!

**Comment by Foadsf** [comment]
@sjackman unfortunately the

    brew install dpo/openblas/mumps

leads to the error message:

~~~
==> Tapping dpo/openblas
Cloning into '/usr/local/Homebrew/Library/Taps/dpo/homebrew-openblas'...
remote: Enumerating objects: 251, done.
remote: Total 251 (delta 0), reused 0 (delta 0), pack-reused 251
Receiving objects: 100% (251/251), 61.10 KiB | 508.00 KiB/s, done.
Resolving deltas: 100% (134/134), done.
Tapped 23 formulae (54 files, 162.4KB).
==> Installing mumps from dpo/openblas
==> Installing dependencies for dpo/openblas/mumps: dpo/openblas/scalapack
==> Installing dpo/openblas/mumps dependency: dpo/openblas/scalapack
==> Downloading http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
######################################################################## 100.0%
==> cmake .. -DBUILD_SHARED_LIBS=ON -DBLAS_LIBRARIES=-L/usr/local/opt/openblas/lib -lopenblas -DLAPACK_LIBRARIES=-L/usr/local/opt/openblas/lib -lopenblas
==> make all
Last 15 lines from /Users/foobar/Library/Logs/Homebrew/scalapack/02.make:
      ierr=MPI_Type_struct(i, len, disp, dtypes, &MyType);
           ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:2850:31: note: expanded from macro 'MPI_Type_struct'
#define MPI_Type_struct(...)  THIS_SYMBOL_WAS_REMOVED_IN_MPI30(MPI_Type_struct, MPI_Type_create_struct)
                              ^
/usr/local/Cellar/open-mpi/4.0.2/include/mpi.h:322:57: note: expanded from macro 'THIS_SYMBOL_WAS_REMOVED_IN_MPI30'
#define THIS_SYMBOL_WAS_REMOVED_IN_MPI30(func, newfunc) _Static_assert(0, #func " was removed in MPI-3.0.  Use " #newfunc " instead.")
                                                        ^
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/dgamx2d_.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/sgamx2d_.c.o] Error 1
make[2]: *** [CMakeFiles/scalapack.dir/BLACS/SRC/igamx2d_.c.o] Error 1
make[1]: *** [CMakeFiles/scalapack.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/dpo/homebrew-openblas/issues

These open issues may also help:
enhancement: much faster build via modern CMake for Scalapack and Mumps https://github.com/dpo/homebrew-openblas/issues/84
~~~

**Comment by Foadsf** [comment]
I have updated the MUMPS installation method [here](https://discourse.brew.sh/t/no-available-formula-with-the-name-mumps/1580/3?u=foadsf).

**Comment by sjackman** [comment]
> unfortunately the `brew install dpo/openblas/mumps` leads to the error message:

Please open an issue at https://github.com/dpo/homebrew-openblas/issues

**Comment by Foadsf** [comment]
@sjackman Thanks for the reply. I will inform them about the issue. But for the moment I have solved some of the issues with compiling Elmer on macOS [here](https://stackoverflow.com/a/60590206/4999991) and have sent a [pull request](https://github.com/ElmerCSC/homebrew-elmerfem/pull/14) for that matter. Though I think it should be reviewed in advance.

**Comment by dpo** [comment]
> Please open an issue at https://github.com/dpo/homebrew-openblas/issues

That tap is inactive. Please use brewsci-num as I indicated in a previous e-mail.

**Comment by Foadsf** [comment]
Dear @dpo that's what I had actually written [here](https://discourse.brew.sh/t/no-available-formula-with-the-name-mumps/1580/3?u=foadsf) and mentioned a couple of comments [above](https://github.com/brewsci/homebrew-science/issues/166#issuecomment-596140463).
