### ISSUE TITLE
Issue  building from source calculix-ccx

### ISSUE THREAD

**Issue by Locost93** [brewsci/homebrew-science#169]
When I attempt to build calculix-ccx from source (ie brew install --build-from-source calculix-ccx) I get an error. Further more the standard install method works but the installed file doesn't seem to work. I'm using macOS High Sierra 10.13.4. Error codes below.

brew install --build-from-source calculix-ccx
==> make -C ccx_2.13/src ccx_2.13 CC=clang FC= CFLAGS=-O2 -I../../spooles -DARCH
Last 15 lines from /Users/tom/Library/Logs/Homebrew/calculix-ccx/03.make:
a - strcpy1.o
a - stress_sen.o
a - strsplt.o
a - tau.o
a - thicknessmain.o
a - tiedcontact.o
a - transitionmain.o
a - u_calloc.o
a - u_free.o
a - u_realloc.o
a - v_betrag.o
a - v_prod.o
a - v_result.o
a - writeheading.o
make: *** [ccx_2.13.a] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

**Comment by sjackman** [comment]
This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

See https://github.com/brewsci/homebrew-science/blob/master/CONTRIBUTING.md
