### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by chandr33** [brewsci/homebrew-science#170]
Last 15 lines from /Users/rochakchandra/Library/Logs/Homebrew/openalpr/02.make:
make[1]: *** [CMakeFiles/alprd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 80%] Linking CXX executable openalpr-utils-calibrate
cd /tmp/openalpr-20180517-25258-10f3ke6/openalpr-2.3.0/src/build/misc_utilities && /usr/local/Cellar/cmake/3.11.1/bin/cmake -E cmake_link_script CMakeFiles/openalpr-utils-calibrate.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/openalpr-utils-calibrate.dir/calibrate.cpp.o  -o openalpr-utils-calibrate -Wl,-rpath,/tmp/openalpr-20180517-25258-10f3ke6/openalpr-2.3.0/src/build/openalpr ../openalpr/libopenalpr.2.dylib ../openalpr/support/libsupport.a /usr/local/opt/opencv@2/lib/libopencv_videostab.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ts.a /usr/local/opt/opencv@2/lib/libopencv_superres.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_stitching.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_contrib.2.4.13.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib /usr/local/opt/opencv@2/lib/libopencv_nonfree.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ocl.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_gpu.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_photo.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_objdetect.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_legacy.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_video.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ml.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_calib3d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_features2d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_highgui.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_imgproc.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_flann.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_core.2.4.13.dylib 
[ 80%] Built target openalpr-utils-calibrate
[ 81%] Linking CXX executable openalpr-utils-binarizefontsheet
cd /tmp/openalpr-20180517-25258-10f3ke6/openalpr-2.3.0/src/build/misc_utilities && /usr/local/Cellar/cmake/3.11.1/bin/cmake -E cmake_link_script CMakeFiles/openalpr-utils-binarizefontsheet.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/openalpr-utils-binarizefontsheet.dir/binarizefontsheet.cpp.o  -o openalpr-utils-binarizefontsheet -Wl,-rpath,/tmp/openalpr-20180517-25258-10f3ke6/openalpr-2.3.0/src/build/openalpr ../openalpr/libopenalpr.2.dylib ../openalpr/support/libsupport.a /usr/local/opt/opencv@2/lib/libopencv_videostab.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ts.a /usr/local/opt/opencv@2/lib/libopencv_superres.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_stitching.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_contrib.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_nonfree.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ocl.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_gpu.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_photo.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_objdetect.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_legacy.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_video.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ml.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_calib3d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_features2d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_highgui.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_imgproc.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_flann.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_core.2.4.13.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib 
[ 82%] Linking CXX executable alpr
/usr/local/Cellar/cmake/3.11.1/bin/cmake -E cmake_link_script CMakeFiles/alpr.dir/link.txt --verbose=1
[ 82%] Built target openalpr-utils-binarizefontsheet
/usr/local/Homebrew/Library/Homebrew/shims/super/clang++   -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/alpr.dir/main.cpp.o  -o alpr -Wl,-rpath,/tmp/openalpr-20180517-25258-10f3ke6/openalpr-2.3.0/src/build/openalpr openalpr/libopenalpr.2.dylib openalpr/support/libsupport.a video/libvideo.a /usr/local/opt/opencv@2/lib/libopencv_videostab.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ts.a /usr/local/opt/opencv@2/lib/libopencv_superres.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_stitching.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_contrib.2.4.13.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib /usr/local/lib/libtesseract.dylib /usr/local/lib/liblept.dylib -lpthread /usr/local/opt/opencv@2/lib/libopencv_nonfree.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ocl.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_gpu.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_photo.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_objdetect.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_legacy.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_video.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_ml.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_calib3d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_features2d.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_highgui.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_imgproc.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_flann.2.4.13.dylib /usr/local/opt/opencv@2/lib/libopencv_core.2.4.13.dylib openalpr/support/libsupport.a 
[ 82%] Built target alpr
make: *** [all] Error 2

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap is not maintained. Consider opening a pull request to migrate this formula to Homebrew/core.
See https://github.com/brewsci/homebrew-science/blob/master/CONTRIBUTING.md
