### ISSUE TITLE
paraview Error: No libpythonX.Y.{dylib|so|a} file found!

### ISSUE THREAD

**Issue by Gwang-Jin** [brewsci/homebrew-science#177]
Hello. Is this tap maintained?

I met an error message when `paraview` installing although python@2 is installed.

````
No libpythonX.Y.{dylib|so|a} file found!
````

How about changing paraview.rb
````
58         python_executable = `which python`.strip
````
to
````
python_executable = Utils.popen_read("which python").strip
````
?
Thank you.

**Comment by jonchang** [comment]
As the issue template states, this tap is not maintained and we don't provide support for it anymore. If you're able to fix this issue, please consider opening a pull request to migrate it to another brewsci tap: https://github.com/brewsci/

**Comment by sjackman** [comment]
Or submit this formula to Homebrew/core If you're able to fix this issue. https://github.com/Homebrew/homebrew-core
