### ISSUE TITLE
Failed ds9 installation

### ISSUE THREAD

**Issue by bleist88** [brewsci/homebrew-science#178]
Just tried to install ds9 and got this error.
"""
brian:~$ brew install brewsci/science/ds9
==> Installing ds9 from brewsci/science
==> Downloading http://ds9.si.edu/archive/source/ds9.7.3.2.tar.gz
Already downloaded: /Users/brian/Library/Caches/Homebrew/ds9-7.3.2.tar.gz
==> make
Last 15 lines from /Users/brian/Library/Logs/Homebrew/ds9/01.make:
inline _LIBCPP_INLINE_VISIBILITY long double tanh(long double __lcpp_x) _NOEXCEPT {return ::tanhl(__lcpp_x);}
                                             ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:1027:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       tanh(float __lcpp_x) _NOEXCEPT       {return ::tanhf(__lcpp_x);}
                                             ^
/usr/include/math.h:371:15: note: candidate function
extern double tanh(double);
              ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/math.h:1034:1: note: candidate template ignored: could not match 'typename std::enable_if<std::is_integral<_A1>::value, double>::type (_A1) throw()' against 'void'
tanh(_A1 __lcpp_x) _NOEXCEPT {return ::tanh((double)__lcpp_x);}
^
15 errors generated.
make[1]: *** [bltVecMath.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [tkblt] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues
"""

**Comment by jonchang** [comment]
As the issue template states, this tap is not maintained and we don't provide support for it anymore. If you're able to fix this issue, please consider opening a pull request to migrate it to another brewsci tap: https://github.com/brewsci/

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
Or submit this formula to Homebrew/core If you're able to fix this issue. https://github.com/Homebrew/homebrew-core
