### ISSUE TITLE
Problem when installing mumps

### ISSUE THREAD

**Issue by dumontsrg** [brewsci/homebrew-science#18]
When I want to install mumps, I have the following issue:

Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:11:in `<class:Mumps>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:14:in `<class:Mumps>'
Please report this to the brewsci/science tap!

==> Installing mumps from brewsci/science
Warning: Calling 'depends_on :mpi' is deprecated!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:11:in `<class:Mumps>'
Please report this to the brewsci/science tap!

Warning: Calling 'depends_on :fortran' is deprecated!
Use 'depends_on "gcc"' instead.
/usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/mumps.rb:14:in `<class:Mumps>'
Please report this to the brewsci/science tap!

==> Downloading http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz
Already downloaded: /Users/serge/Library/Caches/Homebrew/mumps-5.1.1.tar.gz
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/C
Last 15 lines from /Users/serge/Library/Logs/Homebrew/mumps/01.make:
clang -fPIC -I../include -O  -c symbfac.c -o symbfac.o
clang -fPIC -I../include -O  -c interface.c -o interface.o
clang -fPIC -I../include -O  -c sort.c -o sort.o
clang -fPIC -I../include -O  -c minpriority.c -o minpriority.o
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o 
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

How can I fix it ?

Yours

**Comment by dpo** [comment]
Mumps is available here: https://github.com/dpo/homebrew-openblas

**Comment by dumontsrg** [comment]
Thank you, now it works properly.
