### ISSUE TITLE
Error in installing brew install brewsci/science/xrmc (both with and without  --with-xmi-msim)

### ISSUE THREAD

**Issue by NGeorgescu** [brewsci/homebrew-science#180]
==> make check
Making check in src
Making check in arrayNd
make[2]: Nothing to be done for `check'.
Making check in composition
make[2]: Nothing to be done for `check'.
Making check in detector
make[2]: Nothing to be done for `check'.
Making check in device
make[2]: Nothing to be done for `check'.
Making check in exception
make[2]: Nothing to be done for `check'.
Making check in geom3d
make[2]: Nothing to be done for `check'.
Making check in gettoken
make[2]: Nothing to be done for `check'.
Making check in xrmc_algo
make[2]: Nothing to be done for `check'.
Making check in randmt
make[2]: Nothing to be done for `check'.
Making check in photon
make[2]: Nothing to be done for `check'.
Making check in sample
make[2]: Nothing to be done for `check'.
Making check in source
make[2]: Nothing to be done for `check'.
Making check in spectrum
make[2]: Nothing to be done for `check'.
Making check in xrmc_math
make[2]: Nothing to be done for `check'.
Making check in beamsource
make[2]: Nothing to be done for `check'.
Making check in phasecontrast
make[2]: Nothing to be done for `check'.
Making check in fft
make[2]: Nothing to be done for `check'.
Making check in radionuclide
make[2]: Nothing to be done for `check'.
Making check in .
make[2]: Nothing to be done for `check-am'.
Making check in main
make[2]: Nothing to be done for `check'.
Making check in doc
make[1]: Nothing to be done for `check'.
Making check in examples
Making check in cylind_shell
/Library/Developer/CommandLineTools/usr/bin/make  xrmc.sh
echo "../../src/main/xrmc input.dat" > xrmc.sh
chmod a+x xrmc.sh
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
FAIL: xrmc.sh
============================================================================
Testsuite summary for xrmc 6.6.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See examples/cylind_shell/test-suite.log
Please report to golosio@uniss.it
============================================================================
make[4]: *** [test-suite.log] Error 1
make[3]: *** [check-TESTS] Error 2
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

==> Formula
Tap: brewsci/science
Path: /usr/local/Homebrew/Library/Taps/brewsci/homebrew-science/Formula/xrmc.rb
==> Configuration
HOMEBREW_VERSION: 1.6.7
ORIGIN: https://github.com/Homebrew/brew
HEAD: 22e9fd772926e389e264cfb328c3d810b06759f9
Last commit: 30 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: a930ced7bc7f391f9d488d904254f9a9ace1db04
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_ENABLE_AUTO_UPDATE_MIGRATION: 1
CPU: quad-core 64-bit ivybridge
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.1 build 902
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.4-x86_64
CLT: 9.4.0.0.1.1526532315
Xcode: N/A
XQuartz: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: gcc-8
HOMEBREW_CXX: g++-8
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/libxml2:/usr/local/opt/libxslt:/usr/local/opt/gettext:/usr/local/opt/libffi:/usr/local
CMAKE_INCLUDE_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks:/usr/local/opt/python@2/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/isl/lib/pkgconfig:/usr/local/opt/mpfr/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig:/usr/local/opt/xraylib/lib/pkgconfig:/usr/local/opt/gsl/lib/pkgconfig:/usr/local/opt/fgsl/lib/pkgconfig:/usr/local/opt/python@2/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig:/usr/local/opt/libxslt/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/xmi-msim/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13
ACLOCAL_PATH: /usr/local/opt/libxml2/share/aclocal:/usr/local/opt/libxslt/share/aclocal:/usr/local/opt/gettext/share/aclocal:/usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/gcc/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/local/opt/xraylib/bin:/usr/local/opt/gsl/bin:/usr/local/opt/python@2/bin:/usr/local/opt/libxml2/bin:/usr/local/opt/libxslt/bin:/usr/local/opt/gettext/bin:/usr/local/opt/pcre/bin:/usr/local/opt/glib/bin:/usr/local/opt/hdf5/bin:/usr/local/opt/xmi-msim/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: brewsci/science/xrmc 6.6.0 did not build
Logs:
     /Users/nsg/Library/Logs/Homebrew/xrmc/02.configure
     /Users/nsg/Library/Logs/Homebrew/xrmc/00.options.out
     /Users/nsg/Library/Logs/Homebrew/xrmc/02.configure.cc
     /Users/nsg/Library/Logs/Homebrew/xrmc/03.make.cc
     /Users/nsg/Library/Logs/Homebrew/xrmc/01.autoreconf
     /Users/nsg/Library/Logs/Homebrew/xrmc/04.make
     /Users/nsg/Library/Logs/Homebrew/xrmc/config.log
     /Users/nsg/Library/Logs/Homebrew/xrmc/03.make
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

**Comment by jonchang** [comment]
As the [issue template](https://github.com/brewsci/homebrew-science/blob/master/.github/ISSUE_TEMPLATE.md) states, this tap is not maintained and we don't provide support for it anymore. If you're able to fix this issue, please consider opening a pull request to migrate it to another brewsci tap: https://github.com/brewsci/

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
