### ISSUE TITLE
eXpress installation; make error

### ISSUE THREAD

**Issue by mswyers** [brewsci/homebrew-science#182]
Hello, I am attempting to install an annotation package via brew install on my RHEL-7 workstation. When I do, I run into a make error with eXpress.

When attempting to install eXpress, I receive this error:

 
==> Installing express from brewsci/science
==> Downloading https://pachterlab.github.io/eXpress/downloads/express-1.5.1/express-1.5.1-src.tgz
Already downloaded: /home/cwu/.cache/Homebrew/express-1.5.1.tgz
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/linuxbrew/.linuxbrew/Cellar
==> make install
Last 15 lines from /home/cwu/.cache/Homebrew/Logs/express/02.make:
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected '}' before end of line
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected unqualified-id before end of line
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected '}' before end of line
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected '}' before end of line
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected '}' before end of line
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/alignments.pb.h:543:30: error: expected declaration before end of line
In file included from /tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/main.cpp:20:0:
/tmp/express-20180627-38645-i64hxv/express-1.5.1-src/src/main.h:94:14: warning: 'LOG_MAX' defined but not used [-Wunused-variable]
 const double LOG_MAX = log(std::numeric_limits<double>::max());
              ^
make[2]: *** [src/CMakeFiles/express.dir/main.cpp.o] Error 1
make[2]: Leaving directory `/tmp/express-20180627-38645-i64hxv/express-1.5.1-src'
make[1]: *** [src/CMakeFiles/express.dir/all] Error 2
make[1]: Leaving directory `/tmp/express-20180627-38645-i64hxv/express-1.5.1-src'
make: *** [all] Error 2

From there the install fails. Any help resolving this issue would be greatly appreciated.

Best,

Michael

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/brewsci/homebrew-bio

**Comment by sjackman** [comment]
Perhaps you can use `brewsci/bio/salmon` or `kallisto` instead of `express`.
