### ISSUE TITLE
make[2]: dynamiclib: No such file or directory

### ISSUE THREAD

**Issue by rahulmehta87** [brewsci/homebrew-science#19]
==> Downloading http://mumps.enseeiht.fr/MUMPS_5.1.1.tar.gz
Already downloaded: /Users/merahul/Library/Caches/Homebrew/mumps-5.1.1.tar.gz
==> make alllib LIBEXT=.dylib AR= -dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/$(notdir $@) -undefined dynamic_lookup -o  RANLIB=echo OPTF=-O CDEFS=-DAdd_ O
Last 15 lines from /Users/merahul/Library/Logs/Homebrew/mumps/01.make:
clang -fPIC -I../include -O  -c symbfac.c -o symbfac.o
clang -fPIC -I../include -O  -c interface.c -o interface.o
clang -fPIC -I../include -O  -c sort.c -o sort.o
clang -fPIC -I../include -O  -c minpriority.c -o minpriority.o
dynamiclib -Wl,-install_name -Wl,/usr/local/Cellar/mumps/5.1.1_1/lib/libpord.dylib -undefined dynamic_lookup -o libpord.dylib graph.o gbipart.o gbisect.o ddcreate.o ddbisect.o nestdiss.o multisector.o gelim.o bucket.o tree.o symbfac.o interface.o sort.o minpriority.o 
make[2]: dynamiclib: No such file or directory
make[2]: [libpord.dylib] Error 1 (ignored)
echo libpord.dylib
libpord.dylib
if [ "./PORD/lib/" != "" ] ; then \
	  cp ./PORD/lib//libpord.dylib lib/libpord.dylib; \
	fi;
cp: ./PORD/lib//libpord.dylib: No such file or directory
make[1]: *** [lib/libpord.dylib] Error 1
make: *** [c] Error 2

**Comment by sjackman** [comment]
Please enclose copy-and-paste blocks in triple back ticks.
See https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

Your answer is here: https://github.com/brewsci/homebrew-science/issues/18#issuecomment-360466150

**Comment by rahulmehta87** [comment]
When I try to install ipopt, it fails with the above message while installing mumps 5.1.1.

The version of mumps available from dpo/openblas is 5.1.2.

How do I make 'brew install ipopt' use mumps from 'dpo/openblas' rather than from 'brewsci/homebrew-science'?

**Comment by sjackman** [comment]
You can, if you like, open an issue at https://github.com/dpo/homebrew-openblas/issues/new
