### ISSUE TITLE
orocos-kdl has been accepted to homebrew-core

### ISSUE THREAD

**Issue by bblacey** [brewsci/homebrew-science#20]
https://github.com/Homebrew/homebrew-core/blob/master/Formula/orocos-kdl.rb

Therefore the `orocos-kdl` formula should be removed from this tap to avoid conflicts.

**Comment by sjackman** [comment]
Fixed by 1452ffc8868d64a0bb309746ae9e2804be7ecdf6
Thanks for the bug report, Bruce.
👍
