### ISSUE TITLE
Issue installing scotch library

### ISSUE THREAD

**Issue by whamb** [brewsci/homebrew-science#220]
==> Installing scotch from brewsci/science
==> Downloading https://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
Already downloaded: /Users/walham/Library/Caches/Homebrew/downloads/2bd1ac66828c15a1bdf933512b701013a9c8caf78030a82d03da9be8228063a5--scotch_6.0.4.tar.gz
==> make scotch VERBOSE=ON CCS=clang CCP= CCD= RANLIB=echo CFLAGS=-O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_B
==> make ptscotch VERBOSE=ON CCS=clang CCP= CCD= RANLIB=echo CFLAGS=-O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD
Last 15 lines from /Users/walham/Library/Logs/Homebrew/scotch/02.make:
make[2]: `libscotcherrexit.dylib' is up to date.
make CFLAGS="-O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ -DSCOTCH_PTSCOTCH" CC=""	\
					ptscotch.h							\
					ptscotchf.h							\
					libptscotch.dylib						\
					libptscotcherr.dylib						\
					libptscotcherrexit.dylib
O3 -fPIC -Drestrict=__restrict -DCOMMON_PTHREAD_BARRIER -DCOMMON_PTHREAD -DSCOTCH_CHECK_AUTO -DCOMMON_RANDOM_FIXED_SEED -DCOMMON_TIMING_OLD -DSCOTCH_RENAME -DCOMMON_FILE_COMPRESS_BZ2 -DCOMMON_FILE_COMPRESS_GZ -DSCOTCH_PTSCOTCH -DSCOTCH_VERSION=6 -DSCOTCH_RELEASE=0 -DSCOTCH_PATCHLEVEL=4 dummysizes.c -o ptdummysizes -lm -lz -lpthread -lbz2
make[2]: O3: No such file or directory
make[2]: [ptdummysizes] Error 1 (ignored)
./ptdummysizes library_pt.h ptscotch.h
make[2]: ./ptdummysizes: No such file or directory
make[2]: *** [ptscotch.h] Error 1
make[1]: *** [ptscotch] Error 2
make: *** [ptscotch] Error 2

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
