### ISSUE TITLE
superlu

### ISSUE THREAD

**Issue by BlitzGLEP1326** [brewsci/homebrew-science#226]
This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

# Hosting Your Own Tap

Anyone can host their own tap. See [Interesting Taps & Forks](https://docs.brew.sh/Interesting-Taps-and-Forks.html) and [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html)

**Comment by dpo** [comment]
This tap is no longer maintained. Please use https://github.com/brewsci/homebrew-num.
