### ISSUE TITLE
superlu error

### ISSUE THREAD

**Issue by BlitzGLEP1326** [brewsci/homebrew-science#227]
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/superlu_dist/5.1.0_3 -DCMAKE_BUILD
Last 15 lines from /Users/konstantin/Library/Logs/Homebrew/superlu_dist/01.cmake:
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:71 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/tmp/superlu_dist-20190113-2626-1ph20pj/SuperLU_DIST_5.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/superlu_dist-20190113-2626-1ph20pj/SuperLU_DIST_5.1.0/build/CMakeFiles/CMakeError.log".

**Comment by dpo** [comment]
This tap is no longer maintained. Please use https://github.com/brewsci/homebrew-num. However, `superlu_dist` is not yet available. See https://github.com/brewsci/homebrew-num/pull/24.

**Comment by dpo** [comment]
@BlitzGLEP1326 Please try the brewsci-num tap. I just committed bottles for superlu-dist.
