### ISSUE TITLE
Brew upgrade numpy not working

### ISSUE THREAD

**Issue by kaschbacher** [brewsci/homebrew-science#228]
-- I ran brew upgrade numpy
 
-- got this error:
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build_ext.py", line 159, in finalize_options
    self.include_dirs.append(py_include)
AttributeError: 'unicode' object has no attribute 'append'

-- Thanks!

This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

# Hosting Your Own Tap

Anyone can host their own tap. See [Interesting Taps & Forks](https://docs.brew.sh/Interesting-Taps-and-Forks.html) and [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html)

**Comment by sjackman** [comment]
Hi, Kirstin. Please report this error to  https://github.com/Homebrew/homebrew-core. Be sure to fill in the issue template. Good luck sorting it out!
