### ISSUE TITLE
brewsci/science/arb installing problem on Mojave 10.14.4

### ISSUE THREAD

**Issue by rejewski** [brewsci/homebrew-science#238]
I got an error in installing arb on Mojave 10.14.4.
I wrote
brew install brewsci/science/arb
and got the following
-------------------
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing arb from brewsci/science
==> Downloading https://homebrew.bintray.com/bottles-science/arb-2.11.1.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "arb"
Download failed: https://homebrew.bintray.com/bottles-science/arb-2.11.1.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/fredrik-johansson/arb/archive/2.11.1.tar.gz
Already downloaded: /Users/languasc/Library/Caches/Homebrew/downloads/7920f35fc5adfab9fd30d73f833965568100175a5e801547ad3948a692ef0c02--2.11.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/arb/2.11.1 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-flint=/usr/local/opt/flint
==> make
==> make install
==> make check
Last 15 lines from /Users/languasc/Library/Logs/Homebrew/arb/04.make:
det....exp....exp_sum_taylor....PASS
frobenius_norm....PASS
inv....PASS
inv_cho_precomp....PASS
inv_ldl_precomp....PASS
ldl....PASS
lu....PASS
mul....PASS
mul_entrywise....PASS
mul_threaded....make[1]: *** [../build/arb_mat/test/t-mul_threaded_RUN] Abort trap: 6
make[1]: *** Waiting for unfinished jobs....
PASS
PASS
PASS
make: *** [check] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

-------------

Do you have any suggestion? Thanks a  lot !

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported.

**Comment by sjackman** [comment]
You can try `brew edit arb` and deleting the line `make check`.

**Comment by rejewski** [comment]
thanks !
