### ISSUE TITLE
build fail on Mojave

### ISSUE THREAD

**Issue by VirtualEmbryo** [brewsci/homebrew-science#242]
Hello,

I encounter this build issue (Mojave):

[–]$ brew install ome-files
==> Installing ome-files from brewsci/science
==> Installing dependencies for brewsci/science/ome-files: ome-common and ome-xml
==> Installing brewsci/science/ome-files dependency: ome-common
==> Downloading https://downloads.openmicroscopy.org/ome-common-cpp/5.5.0/source/ome-common-cpp-5.5.0.tar.xz
######################################################################## 100.0%
==> Downloading https://github.com/google/googletest/archive/release-1.8.0.tar.gz
==> Downloading from https://codeload.github.com/google/googletest/tar.gz/release-1.8.0
######################################################################## 100.0%
==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ome-common/5.5.0_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFI
==> make install
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/ome-common/5.5.0_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEF
==> make
Last 15 lines from /Users/Turlier/Library/Logs/Homebrew/ome-common/04.make:
make[1]: *** [test/ome-common/CMakeFiles/xalan.dir/all] Error 2
[ 59%] Linking CXX executable xerces
cd /tmp/ome-common-20190502-89835-hk2g6e/ome-common-cpp-5.5.0/build/test/ome-common && /usr/local/Cellar/cmake/3.14.3/bin/cmake -E cmake_link_script CMakeFiles/xerces.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++   -pedantic -Wall -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wextra -Wformat=2 -Wimplicit-atomic-properties -Wmissing-declarations -Wno-long-long -Wnon-virtual-dtor -Woverlength-strings -Woverloaded-virtual -Wredundant-decls -Wreorder -Wswitch-default -Wunused-variable -Wwrite-strings -Wno-variadic-macros -fstrict-aliasing -Wno-unused-local-typedef -Wno-language-extension-token -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/xerces.dir/xerces.cpp.o  -o xerces -Wl,-rpath,/tmp/ome-common-20190502-89835-hk2g6e/ome-common-cpp-5.5.0/build/lib/ome/common ../../lib/ome/test/libome-test.a ../../lib/ome/common/libome-common.5.5.0.dylib /usr/local/lib/libboost_log-mt.dylib /usr/local/lib/libboost_log_setup-mt.dylib /usr/local/lib/libboost_thread-mt.dylib /usr/local/lib/libboost_date_time-mt.dylib /usr/local/lib/libboost_chrono-mt.dylib /usr/local/lib/libboost_atomic-mt.dylib /usr/local/lib/libboost_iostreams-mt.dylib /usr/local/lib/libboost_regex-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libxalan-c.dylib /usr/local/lib/libxerces-c.so /usr/local/lib/libgtest.dylib 
Undefined symbols for architecture x86_64:
  "testing::internal::MakeAndRegisterTestInfo(char const*, char const*, char const*, char const*, testing::internal::CodeLocation, void const*, void (*)(), void (*)(), testing::internal::TestFactoryBase*)", referenced from:
      testing::internal::ParameterizedTestCaseInfo<XercesTest>::RegisterTests() in xerces.cpp.o
      __GLOBAL__sub_I_xerces.cpp in xerces.cpp.o
  "testing::internal::ReportInvalidTestCaseType(char const*, testing::internal::CodeLocation)", referenced from:
      testing::internal::ParameterizedTestCaseInfo<XercesTest>* testing::internal::ParameterizedTestCaseRegistry::GetTestCasePatternHolder<XercesTest>(char const*, testing::internal::CodeLocation) in xerces.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/ome-common/xerces] Error 1
make[1]: *** [test/ome-common/CMakeFiles/xerces.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-science/issues

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
