### ISSUE TITLE
petsc symlink under osx

### ISSUE THREAD

**Issue by jviquerat** [brewsci/homebrew-science#243]
Sorry if that's not the right place to file this issue.
When installing petsc from homebrew, the symlink that is generated seems wrong : 

```
>> ls /usr/local/lib/petsc 
lrwxr-xr-x  1 viquerat  admin    34B May 13 09:01 /usr/local/lib/petsc -> usr/local/Cellar/petsc/3.10.3_2/lib/petsc
```

I would expect it to link to ```/usr/local/Cellar/petsc/3.10.3_2```. The current linking pattern generates conflict when building projects relying on petsc with cmake.

I am using Osx Mojave, 10.14.4.

**Comment by sjackman** [comment]
The best place to ask questions is https://discourse.brew.sh

Are you perhaps looking for the symlink `/usr/local/opt/petsc` which links to `/usr/local/Cellar/petsc/3.10.3_2`?
