### ISSUE TITLE
I am trying to install calculus on Mac OS X Catalina...

### ISSUE THREAD

**Issue by cfernandesINEGI** [brewsci/homebrew-science#254]
make -C ccx_2.13/src ccx_2.13 CC=clang FC= CFLAGS=-O2 -I../../spooles -DARCH
Last 15 lines from /Users/elsasilva/Library/Logs/Homebrew/calculix-ccx/03.make:
a - strcpy1.o
a - stress_sen.o
a - strsplt.o
a - tau.o
a - thicknessmain.o
a - tiedcontact.o
a - transitionmain.o
a - u_calloc.o
a - u_free.o
a - u_realloc.o
a - v_betrag.o
a - v_prod.o
a - v_result.o
a - writeheading.o
make: *** [ccx_2.13.a] Error 1

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
