### ISSUE TITLE
Issue with PETSc and SLEPc

### ISSUE THREAD

**Issue by lberti** [brewsci/homebrew-science#255]
Good morning,

I have the following error when trying to install SLEPc via Homebrew 

```
==> ./configure --prefix=/usr/local/Cellar/slepc/3.7.4_1/real --with-clean=true --with-arpack-dir=/usr/local/opt/arpack/lib --with-arpack-flags=-lparpack,-larpack


./configure
--prefix=/usr/local/Cellar/slepc/3.7.4_1/real
--with-clean=true
--with-arpack-dir=/usr/local/opt/arpack/lib
--with-arpack-flags=-lparpack,-larpack

Checking environment...
ERROR: PETSC_DIR environment variable is not valid
```

Moreover, the SLEPc version that is brewed is 3.7 and it should not be compatible with the current PETSc version.

**Comment by dpo** [comment]
Hi. This repository is no longer maintained and is only here for historical purposes. It's better to use https://github.com/brewsci/homebrew-num but unfortunately, I haven't gotten around to writing an updated formula for SLEPc. If you are willing, I would be happy to review a pull request there with an updated formula.
