### ISSUE TITLE
setup OpenCallada bottle on Catalina

### ISSUE THREAD

**Issue by vserge** [brewsci/homebrew-science#256]
brew install Opencollada
==> Installing opencollada from brewsci/science
==> Downloading https://homebrew.bintray.com/bottles-science/opencollada-1.6.59.sierra.bottle.tar.gz
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "opencollada"
Download failed: https://homebrew.bintray.com/bottles-science/opencollada-1.6.59.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/KhronosGroup/OpenCOLLADA/archive/v1.6.59.tar.gz
Already downloaded: /Users/vserge/Library/Caches/Homebrew/downloads/eb8e82326c5a4c39f57851605d8f1f128465b0263836f1af528518b55331648c--OpenCOLLADA-1.6.59.tar.gz
==> cmake ..
==> make install
Last 15 lines from /Users/vserge/Library/Logs/Homebrew/opencollada/02.make:
[ 24%] Linking CXX static library ../../lib/libbuffer.a
cd /tmp/opencollada-20200426-50002-1jfjkmd/OpenCOLLADA-1.6.59/build/common/libBuffer && /usr/local/Cellar/cmake/3.17.1/bin/cmake -P CMakeFiles/buffer_static.dir/cmake_clean_target.cmake
cd /tmp/opencollada-20200426-50002-1jfjkmd/OpenCOLLADA-1.6.59/build/common/libBuffer && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E cmake_link_script CMakeFiles/buffer_static.dir/link.txt --verbose=1
make[1]: /usr/bin/ar qc ../../lib/libbuffer.a  CMakeFiles/buffer_static.dir/src/CommonBuffer.cpp.o CMakeFiles/buffer_static.dir/src/CommonCharacterBuffer.cpp.o CMakeFiles/buffer_static.dir/src/CommonFWriteBufferFlusher.cpp.o CMakeFiles/buffer_static.dir/src/CommonStreamBufferFlusher.cpp.o
*** [COLLADABaseUtils/CMakeFiles/OpenCOLLADABaseUtils_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ranlib ../../lib/libbuffer.a
[ 24%] Built target buffer_static
[ 24%] Linking CXX static library ../lib/libDAEValidatorLibrary.a
cd /tmp/opencollada-20200426-50002-1jfjkmd/OpenCOLLADA-1.6.59/build/DAEValidator && /usr/local/Cellar/cmake/3.17.1/bin/cmake -P CMakeFiles/DAEValidatorLibrary.dir/cmake_clean_target.cmake
cd /tmp/opencollada-20200426-50002-1jfjkmd/OpenCOLLADA-1.6.59/build/DAEValidator && /usr/local/Cellar/cmake/3.17.1/bin/cmake -E cmake_link_script CMakeFiles/DAEValidatorLibrary.dir/link.txt --verbose=1
/usr/bin/ar qc ../lib/libDAEValidatorLibrary.a  CMakeFiles/DAEValidatorLibrary.dir/library/src/ArgumentParser.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/Dae.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/DaeValidator.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/Log.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/DAEValidatorLibrary.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/PathUtil.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/Strings.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/StringUtil.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/Uri.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlAttribute.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlDoc.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlNamespace.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlNode.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlNodes.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlNodeSet.cpp.o CMakeFiles/DAEValidatorLibrary.dir/library/src/XmlSchema.cpp.o
/usr/bin/ranlib ../lib/libDAEValidatorLibrary.a
[ 24%] Built target DAEValidatorLibrary
make: *** [all] Error 2

---------
but the same time building opencollada from the source without homebrew:
OpenCOLLADA-1.6.68 % cmake -G Xcode -DWITH_IN_SOURCE_BUILD=ON
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Architecture: x86_64
-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibXml2: /usr/lib/libxml2.dylib (found version "2.9.4")
-- SUCCESSFUL: LibXml2 found
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Found PCRE: /usr/local/Cellar/pcre/8.44/include
-- SUCCESSFUL: PCRE found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/vserge/GitHub/OpenCOLLADA-1.6.68

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
