### ISSUE TITLE
Installing flexbar 

### ISSUE THREAD

**Issue by JackCrook** [brewsci/homebrew-science#257]
This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the [Brewsci organization](https://github.com/brewsci). Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.

# Hosting Your Own Tap

Anyone can host their own tap. See [Interesting Taps & Forks](https://docs.brew.sh/Interesting-Taps-and-Forks.html) and [How to Create and Maintain a Tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html)

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
