### ISSUE TITLE
install g2o failed on mac os 10.15

### ISSUE THREAD

**Issue by bli-tamu** [brewsci/homebrew-science#258]
When I tried to install g2o on MacOS 10.15, it failed with the following message:

brew install g2o
==> Installing g2o from brewsci/science
==> Downloading https://homebrew.bintray.com/bottles/metis-5.1.0.catalina.bottle.tar.gz
Already downloaded: /Users/binbinli/Library/Caches/Homebrew/downloads/06807bdc5eac17b81e69795bf781218704c86602a2f737c1e75c9d67fba841d1--metis-5.1.0.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/tbb-2020_U2.catalina.bottle.1.tar.gz
Already downloaded: /Users/binbinli/Library/Caches/Homebrew/downloads/c5d71fd6f64fe878781ad3ee52ccc0e64897064b64beec1106024151a7b7c823--tbb-2020_U2.catalina.bottle.1.tar.gz
==> Downloading https://homebrew.bintray.com/bottles/suite-sparse-5.7.2.catalina.bottle.tar.gz
Already downloaded: /Users/binbinli/Library/Caches/Homebrew/downloads/50854e90b65c727f4b770781211e02988acbf1b9e2ffecef766d5b9143432e41--suite-sparse-5.7.2.catalina.bottle.tar.gz
==> Downloading https://homebrew.bintray.com/bottles-science/g2o-2017-07-30.sierra.bottle.tar.gz
##O=#  #
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "g2o"
Download failed: https://homebrew.bintray.com/bottles-science/g2o-2017-07-30.sierra.bottle.tar.gz

**Comment by sjackman** [comment]
Please surround copied-and-pasted logs with triple back ticks. See [GitHub Help / Quoting Code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code).

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
