### ISSUE TITLE
Unistalling this formula?

### ISSUE THREAD

**Issue by illusion899** [brewsci/homebrew-science#259]
Hi, I'm really new to this and get this formula in order to get scotch (parallel computing package) installed. Unfortunately, it didn't work... Since my MacBook storage is pretty limited, and I can't find a folder from Homebrew to uninstall this formula, I was wondering is there a magic spell I can uninstall this?

it will be great if anyone can help, thanks in advance~

**Comment by dpo** [comment]
Try `brew uninstall scotch`. This tap isn't maintained. You can install scotch using
```
brew tap brewsci/num
brew install brewsci-scotch
```
Feel free to open issues here: https://github.com/brewsci/homebrew-num/issues

**Comment by illusion899** [comment]
> Try `brew uninstall scotch`. This tap isn't maintained. You can install scotch using
> 
> ```
> brew tap brewsci/num
> brew install brewsci-scotch
> ```
> 
> Feel free to open issues here: https://github.com/brewsci/homebrew-num/issues

Thank you so much for the help, it's actually worked! It successfully installed the 6.0.4 version which is perfectly fine with me. 
The ultimate goal I'm trying to reach is using a pretty famous package (https://github.com/geodynamics/specfem2d) in our field. But after running the code and edit the zshrc file, when i run
`./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi`
the message still reads 

## ------ ##
## SCOTCH ##
## ------ ##
checking for scotchfarchinit  in -lscotch... no
checking whether Scotch is usable... no, using bundled scotch instead
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... none needed
checking whether yytext is a pointer... no
checking for bison... bison -y
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
pthread found
SCOTCH is enabled

it will be a lifesaver if you can shine any light into this problem, thanks very very much~

**Comment by dpo** [comment]
@illusion899 I don't know the first thing about specfem2d. Check its `configure` options to specify where to find Scotch and to link with it. Also check `config.log` for more specific error messages.

**Comment by illusion899** [comment]
> @illusion899 I don't know the first thing about specfem2d. Check its `configure` options to specify where to find Scotch and to link with it. Also check `config.log` for more specific error messages.

LOL, I really appreciate the previous advice provided, it already helped me a lot. I guess i was just hoping the slight chance you are also familiar with the package, which was an extremely long shot. 
But again, thank you for the advice earlier, really helped me big time.
