### ISSUE TITLE
issue installing ds9 using homebrew

### ISSUE THREAD

**Issue by xnaxe29** [brewsci/homebrew-science#260]
Hello,

I get this issue while installing ds9 using homebrew (brew install ds9) - 

Last 15 lines from /Users/adarshranjan/Library/Logs/Homebrew/ds9/01.make:
      _TkpGetFontFamilies in libtk8.6.a(tkUnixRFont.o)
      _TkpGetSubFonts in libtk8.6.a(tkUnixRFont.o)
      _GetTkFontAttributes in libtk8.6.a(tkUnixRFont.o)
  "_FcUtf8ToUcs4", referenced from:
      _Tk_DrawChars in libtk8.6.a(tkUnixRFont.o)
      _TkDrawAngledChars in libtk8.6.a(tkUnixRFont.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [wish] Error 1
make[1]: *** Waiting for unfinished jobs....
Installing demo image files to /private/tmp/ds9-20201015-41054-119gcak/saods9/lib/tk8.6/demos/images/
Installing library image files to /private/tmp/ds9-20201015-41054-119gcak/saods9/lib/tk8.6/images/
Installing message catalog files to /private/tmp/ds9-20201015-41054-119gcak/saods9/lib/tk8.6/msgs/
Installing and cross-linking command (.n) docs to /private/tmp/ds9-20201015-41054-119gcak/saods9/man/mann/
make: *** [tk] Error 2

Please help

**Comment by jonchang** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
