### ISSUE TITLE
Error installing rapsearch 2

### ISSUE THREAD

**Issue by sci345** [brewsci/homebrew-science#261]
Goal: To install rapsearch 2

My OS: macOS Catalina 10.15.6

My brew version:
Homebrew 2.5.6
Homebrew/homebrew-core (git revision 98f629; last commit 2020-10-23)
Homebrew/homebrew-cask (git revision 2d203; last commit 2020-10-23)

Received error below after running: brew install brewsci/science/rapsearch2
---------------------------------------------------
==> Installing rapsearch2 from brewsci/science
==> Downloading https://downloads.sourceforge.net/project/rapsearch2/RAPSearch2.
Already downloaded: /Users/SharlineMadera/Library/Caches/Homebrew/downloads/019130952bdeac4d477eec91b2444faaafd7c1b31bcc4429bedb610969b7d1f4--RAPSearch2.24_64bits.tar.gz
==> make INC=-I/usr/local/opt/boost/include LIBS=-L/usr/local/opt/boost/lib
Last 15 lines from /Users/SharlineMadera/Library/Logs/Homebrew/rapsearch2/01.make:
^
/usr/local/opt/boost/include/boost/iterator/distance.hpp:49:9: note: candidate function [with SinglePassIterator = std::__1::__wrap_iter<CHitUnit *>]
        distance(SinglePassIterator first, SinglePassIterator last)
        ^
HashSearch.cpp:2556:13: error: call to 'distance' is ambiguous
                        else if (distance(itStart, itEnd) == 1)
                                 ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:698:1: note: candidate function [with _InputIter = std::__1::__wrap_iter<CHitUnit *>]
distance(_InputIter __first, _InputIter __last)
^
/usr/local/opt/boost/include/boost/iterator/distance.hpp:49:9: note: candidate function [with SinglePassIterator = std::__1::__wrap_iter<CHitUnit *>]
        distance(SinglePassIterator first, SinglePassIterator last)
        ^
9 errors generated.
make: *** [HashSearch.o] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-science/issues
---------------------------------------------------

Having a hard time identifying the error and how to overcome it. Any recs appreciated

**Comment by sjackman** [comment]
This tap Brewsci/science is retired and unsupported. If you're able to resolve this issue, consider submitting this formula to https://github.com/Homebrew/homebrew-core
