### ISSUE TITLE
gnudatalanguage not installed from brew

### ISSUE THREAD

**Issue by gppnst** [brewsci/homebrew-science#266]
Hi, 

I am trying to brew install gnudatalanguage but I encounter several errors. When tapping brewsci/science, several errors appear because 'depends_on:java is disabled'.
I am using a Mac OS X machine with Big Sur installed.

**Comment by jonchang** [comment]
> This tap is not maintained. Please consider opening a pull request to migrate this formula to Homebrew/core or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
