### ISSUE TITLE
Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/des.rb des: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.

### ISSUE THREAD

**Issue by impressostudios** [brewsci/homebrew-science#271]
$ brew tap brewsci/homebrew-science
Updating Homebrew...
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Tapping brewsci/science
Cloning into '/opt/homebrew/Library/Taps/brewsci/homebrew-science'...
remote: Enumerating objects: 39, done.
remote: Counting objects: 100% (39/39), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 35571 (delta 23), reused 18 (delta 10), pack-reused 35532
Receiving objects: 100% (35571/35571), 9.36 MiB | 23.55 MiB/s, done.
Resolving deltas: 100% (22677/22677), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/des.rb
des: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/des.rb:15

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/xfig.rb:14

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/openni2.rb
openni2: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/openni2.rb:22

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/slepc.rb:25

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/macse.rb
macse: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/macse.rb:17

Warning: Calling depends_on :x11 is deprecated! Use depends_on specific X11 formula(e) instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/trilinos.rb:29

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/paxtools.rb
paxtools: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/paxtools.rb:7

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/bpipe.rb
bpipe: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/bpipe.rb:13

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/bam2wig.rb
bam2wig: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/bam2wig.rb:10

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/sequel.rb
sequel: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/sequel.rb:19

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/mallet.rb
mallet: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/mallet.rb:18

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/libsigrokdecode.rb
libsigrokdecode: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/libsigrokdecode.rb:70

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/cytoscape.rb
cytoscape: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/cytoscape.rb:17

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/rampart.rb
rampart: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/rampart.rb:21

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/simpleitk.rb
simpleitk: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/simpleitk.rb:33

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/igvtools.rb
igvtools: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/igvtools.rb:19

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/deeplearning4j-cli.rb
deeplearning4j-cli: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/deeplearning4j-cli.rb:10

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/alien-hunter.rb
alien-hunter: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/alien-hunter.rb:19

Error: Invalid formula: /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/multi-worm-tracker.rb
multi-worm-tracker: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.
Please report this issue to the brewsci/science tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/brewsci/homebrew-science/Formula/multi-worm-tracker.rb:19

Error: Cannot tap brewsci/science: invalid syntax in tap!

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
