### ISSUE TITLE
Scamp bottle issue with CDS client

### ISSUE THREAD

**Issue by lonewolf1870** [brewsci/homebrew-science#275]
Hi,

note that the scamp bottle is requiring the cds-client package, but the link is not working.
To make it work (without changing anything else in the bottle), I first had to install the client separately.
This is the error message:

````
brew install scamp

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 1 formula.

==> Installing scamp from brewsci/science
==> Downloading https://archive.org/download/brewsci/bottles-science/cdsclient-3.84.high_sierra.bottle.tar.gz
==> Downloading from https://ia801403.us.archive.org/33/items/brewsci/bottles-science/cdsclient-3.84.high_sierra.bottle.tar.gz
#=#=-#  #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "cdsclient"
Download failed: https://archive.org/download/brewsci/bottles-science/cdsclient-3.84.high_sierra.bottle.tar.gz
````

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
