### ISSUE TITLE
New bottles

### ISSUE THREAD

**Issue by lonewolf1870** [brewsci/homebrew-science#276]
Please note that installations of Sextractor and especially Scamp are years old.
Following what was done for these versions, I adapted the bottles to work with latest (Dec. 2020) versions. You can find them here:

Sextractor bottle: https://gist.github.com/lonewolf1870/102924c2ae2456874173e67bb44e8307#file-sextractor-rb
Scamp bottle: https://gist.github.com/lonewolf1870/102924c2ae2456874173e67bb44e8307#file-scamp-rb

Regards

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
