### ISSUE TITLE
brew install crfsuite failed on M1 MacOS Monetary

### ISSUE THREAD

**Issue by lingamoorthi-ankam-litera-com** [brewsci/homebrew-science#295]
lingamoorthi.ankam@LingamorthysMBP ~ % brew install crfsuite
==> Downloading https://github.com/downloads/chokkan/crfsuite/crfsuite-0.12.tar.gz
Already downloaded: /Users/lingamoorthi.ankam/Library/Caches/Homebrew/downloads/3b692f540345f335f203e8aa30a52e7279cba5d08e285130f811a02b565d8c46--crfsuite-0.12.tar.gz
==> Installing crfsuite from brewsci/science
==> ./configure --prefix=/opt/homebrew/Cellar/crfsuite/0.12
==> make install
Last 15 lines from /Users/lingamoorthi.ankam/Library/Logs/Homebrew/crfsuite/02.make:
Making install in include
make[2]: Nothing to be done for `install-exec-am'.
test -z "/opt/homebrew/Cellar/crfsuite/0.12/include" || .././install-sh -c -d "/opt/homebrew/Cellar/crfsuite/0.12/include"
 /usr/bin/install -c -m 644 crfsuite.h crfsuite_api.hpp crfsuite.hpp '/opt/homebrew/Cellar/crfsuite/0.12/include'
Making install in lib/cqdb
/bin/sh ../../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../include -I.   -I./include -mfpmath=sse -msse2 -DUSE_SSE -O3 -fomit-frame-pointer -ffast-math -Winline -std=c99  -c -o libcqdb_la-lookup3.lo `test -f 'src/lookup3.c' || echo './'`src/lookup3.c
/bin/sh ../../libtool  --tag=CC   --mode=compile clang -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../include -I.   -I./include -mfpmath=sse -msse2 -DUSE_SSE -O3 -fomit-frame-pointer -ffast-math -Winline -std=c99  -c -o libcqdb_la-cqdb.lo `test -f 'src/cqdb.c' || echo './'`src/cqdb.c
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../include -I. -I./include -mfpmath=sse -msse2 -DUSE_SSE -O3 -fomit-frame-pointer -ffast-math -Winline -std=c99 -c src/lookup3.c  -fno-common -DPIC -o .libs/libcqdb_la-lookup3.o
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../../include -I. -I./include -mfpmath=sse -msse2 -DUSE_SSE -O3 -fomit-frame-pointer -ffast-math -Winline -std=c99 -c src/cqdb.c  -fno-common -DPIC -o .libs/libcqdb_la-cqdb.o
error: unknown FP unit 'sse'
error: unknown FP unit 'sse'
make[1]: *** [libcqdb_la-cqdb.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [libcqdb_la-lookup3.lo] Error 1
make: *** [install-recursive] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/brewsci/homebrew-science/issues

lingamoorthi.ankam@LingamorthysMBP ~ % 

My OS is: Mac OS Monetary M1 chip with Rosetta installed
All tools are uptodate

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
