### ISSUE TITLE
Failed Tisean download

### ISSUE THREAD

**Issue by faimai00** [brewsci/homebrew-science#302]
Hello, 

I have tried installing Tisean using Homebrew (brew tap brewsci/science + brew install tisean) but this returns me the following message:
==> Downloading https://archive.org/download/brewsci/bottles-science/tisean-3.0.1_4.sierra.bottle.tar.gz 
==> Downloading from https://ia801805.us.archive.org/0/items/brewsci/bottles-science/tisean-3.0.1_4.sierra.bottle.tar.gz 
-#O#- # #
curl: (22) The requested URL returned error: 404
Error: tisean: Failed to download resource "tisean"
Download failed: https://archive.org/download/brewsci/bottles-science/tisean-3.0.1_4.sierra.bottle.tar.gz

See screenshot:
<img width="900" alt="191047760-c60a3879-526f-4fd6-9e70-914de8f825ff" src="https://user-images.githubusercontent.com/63585229/191366073-b75d8bc2-e5ed-4b1b-9a30-c385698b6a71.png">

I think that the file it is trying to download does not exist at that address so that is why the download fails. I thought it might be useful to notify you in case you wish to update the file directory? 

Many thanks!
Irene

**Comment by jonchang** [comment]
This tap is not maintained. We are not accepting new pull requests, except to migrate a formula to Homebrew/core, Brewsci/bio, or a different tap within the Brewsci organization. Please open an issue if you are interested in creating and maintaining a new tap within the Brewsci organization.
