### ISSUE TITLE
Update pull request template

### ISSUE THREAD

**Issue by heuermh** [brewsci/homebrew-science#4]
Should the following text be removed from the pull request template?

New formula:

We will no longer accept new formula in homebrew-science, as this tap is being phased out.
Please consider submitting your formulae to https://github.com/Homebrew/homebrew-core or host it in your own tap (https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap.html).

**Comment by sjackman** [comment]
I'm not accepting any new PR to Homebrew/science, other than to remove the formulae as they're migrated to other taps. You can submit popular/notable formulae to https://github.com/Homebrew/homebrew-core and bioinformatics formulae to https://github.com/brewsci/homebrew-bio. I'm in the process of getting CI up and running on Brewsci/bio for both Linux and macOS. Linux is working now. macOS should be soon. I'll update the documentation in this repo with this information once CI is up and running in Brewsci/bio.

**Comment by heuermh** [comment]
Thanks for the clarification!
