### ISSUE TITLE
problems installing NEST--HEAD

### ISSUE THREAD

**Issue by andraderenew** [brewsci/homebrew-science#73]
Renes-MacBook-Air-2:~ andraderenew$ brew install NEST --HEAD
==> Installing nest from brewsci/science
==> Installing dependencies for brewsci/science/nest: numpy, mpfr, scipy, freetype
==> Installing brewsci/science/nest dependency: numpy
==> Downloading https://homebrew.bintray.com/bottles/numpy-1.14.1_1.high_sierra.
==> Downloading from https://akamai.bintray.com/60/60b6d4a20734d849394a15744341a
######################################################################## 100.0%
==> Pouring numpy-1.14.1_1.high_sierra.bottle.tar.gz
==> Caveats
If you use system python (that comes - depending on the OS X version -
with older versions of numpy, scipy and matplotlib), you may need to
ensure that the brewed packages come earlier in Python's sys.path with:
  mkdir -p /Users/andraderenew/Library/Python/2.7/lib/python/site-packages
  echo 'import sys; sys.path.insert(1, "/usr/local/lib/python3.6/site-packages")' >> /Users/andraderenew/Library/Python/2.7/lib/python/site-packages/homebrew.pth

Python modules have been installed and Homebrew's site-packages is not
in your Python sys.path, so you will not be able to import the modules
this formula installed. If you plan to develop with these modules,
please run:
  mkdir -p /Users/andraderenew/Library/Python/2.7/lib/python/site-packages
  echo 'import site; site.addsitedir("/usr/local/lib/python3.6/site-packages")' >> /Users/andraderenew/Library/Python/2.7/lib/python/site-packages/homebrew.pth
==> Summary
🍺  /usr/local/Cellar/numpy/1.14.1_1: 939 files, 27MB
==> Installing brewsci/science/nest dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.1.high_sierra.bott
==> Downloading from https://akamai.bintray.com/22/223ac973eb796b275cf751111c458
######################################################################## 100.0%
==> Pouring mpfr-4.0.1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.0.1: 28 files, 4.6MB
==> Installing brewsci/science/nest dependency: scipy
==> Downloading https://homebrew.bintray.com/bottles/scipy-1.0.0_3.high_sierra.b
==> Downloading from https://akamai.bintray.com/39/392b0e6898425a895441cbc4919c4
######################################################################## 100.0%
==> Pouring scipy-1.0.0_3.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/scipy/1.0.0_3: 982 files, 59.5MB
==> Installing brewsci/science/nest dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.9.high_sierra.bo
==> Downloading from https://akamai.bintray.com/29/2978dbec18cf06827ddc93ee04262
######################################################################## 100.0%
==> Pouring freetype-2.9.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.9: 60 files, 2.7MB
==> Installing brewsci/science/nest --HEAD
==> Cloning https://github.com/nest/nest-simulator.git
Cloning into '/Users/andraderenew/Library/Caches/Homebrew/nest--git'...
remote: Counting objects: 1493, done.
remote: Compressing objects: 100% (1260/1260), done.
remote: Total 1493 (delta 463), reused 593 (delta 218), pack-reused 0
Receiving objects: 100% (1493/1493), 7.62 MiB | 442.00 KiB/s, done.
Resolving deltas: 100% (463/463), done.
==> Checking out branch master
==> Downloading https://files.pythonhosted.org/packages/58/a5/0dc93c3ec33f4e2818
Already downloaded: /Users/andraderenew/Library/Caches/Homebrew/nest--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cel
Last 15 lines from /Users/andraderenew/Library/Logs/Homebrew/nest/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/usr/local/Cellar/nest/HEAD-e4e9ad6_1/libexec/nose
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/brewsci/homebrew-science/issues

**Comment by sjackman** [comment]
This tap is not maintained. There is a PR to migrate `nest` to Homebrew/core. https://github.com/Homebrew/homebrew-core/pull/24908
