### ISSUE TITLE
Migrating randy3k/homebrew-r

### ISSUE THREAD

**Issue by randy3k** [brewsci/homebrew-science#74]
Hi @sjackman,

I am interested in migrating https://github.com/randy3k/homebrew-r to brewsci. I have been trying a model of bottling based on github releases. The procedure is as follows: say if one wants to bottle `rstudio-server-1.1.419`, one will need to create a branch `rstudio-server-1.1.419#bottle` (with `#bottle` suffix) and push it to github. The circle ci service will then be triggered: the bottles will be created and uploaded to github releases. At last, a pull request about the bottling information will be made (see this [PR](https://github.com/randy3k/homebrew-r/pull/35/files) for an example).

One major issue of my approach is that it doesn't build bottles directly from PR. I would need to create a branch in order to bottle each formula. However, I think it is not a big issue for a small tap. Especially, I don't have to deal with the potential hassles of bintray and amazon lambda services.

Nevertheless, I am open to switching to the model of using bintray once `homebrew-r` is migrated.

**Comment by sjackman** [comment]
I think your idea of hosting bottles on GitHub is a good one. Since we already have the infrastructure set up for using Bintray, I'd prefer to use that for all taps within the Brewsci organization.

Please move your formulae to a `Formula/` subdirectory.

**Comment by sjackman** [comment]
Please move your formulae to a `Formula/` subdirectory.

**Comment by sjackman** [comment]
Do you intend to support and bottles for both macOS and Linux?

**Comment by sjackman** [comment]
What's the reason for having `cairo-x11` and `r-x11`? On linux these two already use X11 by default. On macOS, why not use Aqua?

**Comment by sjackman** [comment]
What's the reason for having both `boost-rstudio-server` and `rstudio-server`?

**Comment by sjackman** [comment]
A number of the resources used by `rstudio-server` should I suspect work fine with the version in Homebrew/core, for example `pandoc` and `pandoc-citeproc`. Wherever possible I'd prefer to use the Brewed versions of these dependencies rather than vendor in resources. It'll make the formula more maintainable.

**Comment by sjackman** [comment]
I'm happy to have `rstudio-server` in the Brewsci organization. I'm hesitant to create a new tap for essentially a single formula, `rstudio-server`. Do you foresee this proposed `brewsci/r` tap gaining more formulae? I'm wondering if we shouldn't create a `brewsci/sci` or `brewsci/base` or perhaps `brewsci/stats` tap for this formulae.

**Comment by randy3k** [comment]
> Since we already have the infrastructure set up for using Bintray, I'd prefer to use that for all taps within the Brewsci organization

Great

> Please move your formulae to a Formula/ subdirectory.

will do

> Do you intend to support and bottles for both macOS and Linux?

Yes. I am. I have actually built the bottles for `rstudio-server` and `boost-rstudio-server`.

> What's the reason for having cairo-x11 and r-x11? On Linux these two already use X11 by default. On macOS, why not use Aqua?

These two formulas are not useful on linux. Homebrew doesn't support building with x11, see [this](https://github.com/Homebrew/homebrew-core/pull/24433) and [this](https://github.com/Homebrew/homebrew-core/issues/19557). But X11 is needed to open some of the Tcl/Tk applications.

> What's the reason for having both boost-rstudio-server and rstudio-server

`boost-rstudio-server` is actually just boost 1.53 just is a dependency of `rstudio-server`. I have tried to push a versioned formula for boost to Homebrew/core but it was rejected. And I also failed to patch rstudio to compatible with the current boost version (it is too much investigation). So I decided just to tap a version of boost designated to `rstudio-server`.

>  I'm wondering if we shouldn't create a brewsci/sci or brewsci/base or perhaps brewsci/stats tap for this formulae

`brewsci/stats` is a good one 👍

**Comment by randy3k** [comment]
> A number of the resources used by rstudio-server should I suspect work fine with the version in Homebrew/core, for example pandoc and pandoc-citeproc

The binaries were shipped by rstudio. I haven't tried to replace them with the `Homebrew/core` binaries as I was not sure if rstudio has modified them.

**Comment by randy3k** [comment]
Maybe you could create an empty repo, say `homebrew-stats` then I make PRs to that repo.

**Comment by sjackman** [comment]
> These two formulas are not useful on linux. Homebrew doesn't support building with x11, see this and this. But X11 is needed to open some of the Tcl/Tk applications.

Can we drop support for these Tcl/Tk applications on macOS? How often are they used by folk?

Alternatively, can we use the cask R rather than brewed R? `brew cask install r-app` installs the R package distributed by CRAN. I prefer it over the Brewed R, because it can install binary R packages, whereas the brewed R cannot.
https://github.com/caskroom/homebrew-cask/blob/master/Casks/r-app.rb

> boost-rstudio-server is actually just boost 1.53 just is a dependency of rstudio-server. 

I'd suggest using a resource rather than a separate formula for this purpose.

> Maybe you could create an empty repo, say homebrew-stats then I make PRs to that repo.

Unless you foresee other stats formulae being contributed in the near future, I'm inclined to name this new tap something like `brewsci/base`, `brewsci/core`, or `brewsci/sci`.

**Comment by randy3k** [comment]
> Alternatively, can we use the cask R rather than brewed R?

 I could keep the `r-x11` formula for own use if you don't incline to include it. `rstudio-server` is main dish. It is true that `brew cask` is an alternative.

> I'd suggest using a resource rather than a separate formula for this purpose. Have you opened a bug upstream with RStudio? Perhaps they'd fix it.

I am not sure if there is any official binary distribution of boost and I hate to compile the binaries myself and upload it to a random storage. Making a formula seems to be the less trouble way to handle it. I don't expect any users to install `boost-rstudio-server` directly.

I am quite sure that the current release version of rstudio is not compatible with the current boost (v1.66). In fact, the master branch of rstudio is built against boost v1.63 but I am not sure how compatible it is with v1.66.

> I'm inclined to name this new tap something like brewsci/base, brewsci/core, or brewsci/sci.

I am happy with any of your decision. I just feel I should put rstudio-server to a better-maintained tap because quite a number of people are using it.

**Comment by sjackman** [comment]
>> I'd suggest using a resource rather than a separate formula for this purpose. Have you opened a bug upstream with RStudio? Perhaps they'd fix it.

> I am quite sure that the current release version of rstudio is not compatible with the current boost (v1.66). In fact, the master branch of rstudio is built against boost v1.63 but I am not sure how compatible it is with v1.66.

Have you opened a bug upstream with RStudio? Perhaps they would be inclined to fix it.
https://github.com/rstudio/rstudio/issues/new

> I am not sure if there is any official binary distribution of boost and I hate to compile the binaries myself and upload it to a random storage. Making a formula seems to be the less trouble way to handle it. I don't expect any users to install boost-rstudio-server directly.

I meant include the boost source code as a resource, and build it in the `rstudio-server` formula. Do you know whether `rstudio-server` links against the compiled Boost libraries, or does it only use the headers? You can use `brew linkage rstudio-server` to answer this question.  If we keep it as a formula, we can name it `boost@1.63`, since it's not expected to conflict with Homebrew/core.

**Comment by randy3k** [comment]
> Have you opened a bug upstream with RStudio? Perhaps they would be inclined to fix it.
https://github.com/rstudio/rstudio/issues/new

I haven't submit a bug report for this particular boost version (v1.66) but I have raised similar issues earlier about libstdc++ vs libc++; boost 1.55 vs 1.60; java 8 vs 9. And their replies were generic saying that rstudio only support xxx version. That's why I made these [changes](https://github.com/rstudio/rstudio/commits?author=randy3k) to rstudio.

> You can use brew linkage rstudio-server to answer this question. 

Yes, it does link to boost static libraries in build time. `boost@1.63` sounds good to me.

**Comment by sjackman** [comment]
I'll think about a name for the tap and get back to you.

**Comment by sjackman** [comment]
How do you feel about contributing `rstudio-server` to Linuxbrew/bio? We can always migrate the formula if a more appropriately named tap is created in the future.

**Comment by randy3k** [comment]
As `rstudio-server` is a general statistical software, I'd prefer something more "neutral", I will continue hosting it on my own repo before we come up with a more appropriate tap.

**Comment by sjackman** [comment]
How about `brewsci/base`?

**Comment by randy3k** [comment]
I am still interested. `rstudio-server` depends on `boost@1.63`, should I also submit it to `brewsci/base`?

**Comment by sjackman** [comment]
Yes, please do.

**Comment by randy3k** [comment]
@sjackman 
I am trying to push `boost@163` but I got this
```
(randymbpro)-~$ brew audit --strict brewsci/base/boost@163
brewsci/base/boost@163:
  * boost@163 is versioned but no boost formula exists
Error: 1 problem in 1 formula
```

[boost@163.rb](https://github.com/randy3k/homebrew-base/blob/1e600e15c19f0c1791aecc9871210f1d11fc0ddc/Formula/boost@163.rb#L15-L15)

**Comment by sjackman** [comment]
It ought to be named `boost@1.63`, but that's probably not causing this issue. Try it thought, just in case. If the issue persists, I guess it means that versioned formula have to be in the same tap. If that's the case, name it `boost-rstudio-server` or perhaps `rstudio-server-boost`. You could also bundle it in `rstudio-server` as a resource, which makes more sense I think.

**Comment by sjackman** [comment]
@randy3k opened a PR to submit `rstudio-server` to Brewsci/base.
See https://github.com/brewsci/homebrew-base/pull/5
