### ISSUE TITLE
Migrate formulae to Homebrew/core and Brewsci/bio

### ISSUE THREAD

**Issue by sjackman** [brewsci/homebrew-science#9]
Popular or notable formulae can be migrated to [Homebrew/core](https://github.com/homebrew/homebrew-core).
Bioinformatics formulae can be migrated to [Brewsci/bio](https://github.com/brewsci/homebrew-bio).

Metrics of popularity (number of installations) and notariety (GitHub watchers, stars, forks)

+ [Bioinformatics formulae](https://gist.github.com/sjackman/d1db0d73597b674bb23b51221a2914cd#file-metrics-bioinformatics-macos-tsv)
+ [All formulae](https://gist.github.com/sjackman/d1db0d73597b674bb23b51221a2914cd#file-metrics-science-macos-tsv)

- [ ] a5
- [ ] abacas
- [ ] abyss-explorer
- [ ] ace-corrector
- [x] adam
- [ ] adapterremoval
- [ ] afra
- [ ] alien-hunter
- [ ] allpaths-lg
- [ ] amos
- [ ] analysis
- [ ] andi
- [ ] anvio
- [x] aragorn
- [x] arcs
- [ ] art
- [x] artemis
- [ ] astral
- [ ] atram
- [x] augustus
- [ ] bam-readcount
- [ ] bam2wig
- [ ] bamhash
- [ ] bamm
- [ ] bamutil
- [x] barrnap
- [ ] bbtools
- [ ] bcalm
- [ ] beagle
- [ ] beast2
- [ ] beetl
- [ ] bfc
- [ ] bioawk
- [ ] biobloomtools
- [ ] biointerchange
- [ ] biomake
- [ ] biopieces
- [ ] blasr
- [ ] blast
- [ ] blat
- [ ] bless
- [ ] bowtie
- [ ] bpipe
- [ ] breseq
- [x] busco
- [x] canu
- [ ] cap3
- [ ] cd-hit
- [ ] cegma
- [ ] celera-assembler
- [ ] centrifuge
- [ ] cerulean
- [ ] circlator
- [ ] clark
- [ ] clonalframeml
- [ ] clonehd
- [x] clustal-omega
- [x] clustal-w
- [ ] corset
- [ ] cutadapt
- [ ] cytoscape
- [ ] daligner
- [ ] dazz_db
- [ ] delly
- [ ] dextractor
- [ ] dida
- [ ] discovar
- [ ] discovardenovo
- [ ] dsk
- [ ] dwgsim
- [x] e-mem
- [ ] edirect
- [ ] ensembl-tools
- [x] exonerate
- [ ] express
- [ ] fasta
- [ ] fastml
- [ ] fastq-tools
- [ ] fasttree
- [ ] fastuniq
- [ ] fastx_toolkit
- [ ] fermi
- [ ] fermi-lite
- [ ] fermi2
- [ ] fermikit
- [x] flash
- [ ] flexbar
- [ ] fqzcomp
- [ ] freebayes
- [ ] freec
- [ ] fsa
- [x] fwdpp
- [ ] gaemr
- [ ] garli
- [ ] gatb
- [x] gatk
- [ ] geneid
- [ ] genewise
- [ ] gingr
- [ ] glimmerhmm
- [ ] gmap-gsnap
- [ ] grabix
- [ ] graphlan
- [ ] gubbins
- [ ] harvest-tools
- [ ] hisat
- [ ] hisat2
- [ ] hlaminer
- [x] hmmer
- [ ] hmmer2
- [ ] htsbox
- [ ] humann2
- [ ] idba
- [ ] igvtools
- [ ] impute2
- [x] infernal
- [ ] iqtree
- [ ] iva
- [ ] jellyfish
- [ ] jellyfish-1.1
- [ ] kaiju
- [x] kat
- [x] kent-tools
- [ ] kmacs
- [x] kmc
- [ ] kmergenie
- [ ] kmerstream
- [ ] kollector
- [ ] kraken
- [ ] last
- [ ] lastz
- [ ] libbigwig
- [ ] libpll
- [x] libsequence
- [x] lighter
- [ ] links-scaffolder
- [ ] lobstr
- [ ] lrsim
- [ ] lsd
- [ ] lumpy-sv
- [ ] macse
- [ ] mafft
- [x] maker
- [ ] mapsembler2
- [ ] maq
- [x] mash
- [ ] masurca
- [ ] mcl
- [ ] megahit
- [x] meme
- [ ] meraculous
- [x] metaphlan
- [ ] methpipe
- [ ] mhap
- [x] minced
- [ ] minia
- [x] miniasm
- [ ] minimap
- [x] mir-prefer
- [ ] mira
- [ ] mitofy
- [ ] mlst
- [x] mothur
- [ ] mrbayes
- [ ] multi-worm-tracker
- [x] mummer
- [ ] muscle
- [x] nanopolish
- [ ] ncbi-c++-toolkit
- [ ] ncl
- [ ] newick-utils
- [ ] newicktools
- [ ] nextflow
- [ ] nonpareil
- [ ] novoalign
- [x] ntcard
- [ ] nxtrim
- [ ] oases
- [ ] ogdraw
- [x] oma
- [ ] orthofinder
- [x] paml
- [ ] pandaseq
- [ ] parsnp
- [ ] pathd8
- [x] pathvisio
- [ ] pbsuite
- [ ] pear
- [ ] phipack
- [ ] phlawd
- [ ] phylip
- [x] phyml
- [ ] phyutility
- [ ] phyx
- [ ] piler
- [ ] pilercr
- [x] pilon
- [ ] platypusvar
- [ ] plink
- [ ] plink2
- [ ] poa
- [ ] populations
- [ ] poretools
- [ ] prokka
- [ ] proteinortho
- [ ] psmc
- [ ] quaff
- [ ] quake
- [ ] quast
- [ ] quest
- [x] quicktree
- [ ] quorum
- [ ] r8s
- [x] racon
- [ ] rampart
- [ ] rapsearch2
- [x] raxml
- [ ] ray
- [ ] rcorrector
- [ ] readseq
- [ ] readsim
- [ ] reapr
- [ ] recon
- [x] repeatmasker
- [ ] repeatmodeler
- [ ] repeatscout
- [x] rmblast
- [ ] rna-star
- [ ] rnammer
- [ ] ropebwt2
- [ ] sailfish
- [x] salmon
- [ ] sambamba
- [ ] samblaster
- [ ] samtools@0.1
- [ ] scarpa
- [ ] sdsl-lite
- [ ] seq-gen
- [ ] seqan
- [ ] seqdb
- [ ] sequel
- [x] sga
- [ ] shrimp
- [ ] sickle
- [ ] simulate-pcr
- [ ] skewer
- [ ] smalt
- [ ] smrtanalysis
- [x] snap
- [ ] snap-aligner
- [x] snoscan
- [ ] snp-sites
- [ ] snpeff
- [ ] soapdenovo
- [ ] sortmerna
- [ ] spaced
- [ ] spici
- [ ] squeezambler
- [ ] ssake
- [ ] stacks
- [x] stringtie
- [ ] swarm
- [ ] tabtk
- [ ] tagdust
- [ ] tasr
- [x] tbl2asn
- [ ] tophat
- [ ] trans-abyss
- [ ] trans_proteomic_pipeline
- [x] transdecoder
- [ ] transrate-tools
- [x] trf
- [ ] trimadap
- [x] trimal
- [x] trimmomatic
- [ ] trinity
- [x] trnascan
- [ ] ucsc-genome-browser
- [x] unicycler
- [ ] uproc
- [ ] vague
- [ ] varscan
- [ ] vcake
- [ ] vcflib
- [ ] velvet
- [ ] velvetoptimiser
- [x] viennarna
- [ ] vsearch
- [ ] vt
- [ ] weblogo
- [ ] wiggletools
- [ ] yaha

**Comment by scpeters** [comment]
For the formulae that didn't already go into core, is there a way to redirect from `homebrew/science` to this tap? My colleague was very confused that `homebrew/science/matplotlib` could not be found, but it would be nice if they could get a notice to check `brewsci/science/matplotlib`. Maybe this is an issue for `brew`?

**Comment by sjackman** [comment]
> For the formulae that didn't already go into core, is there a way to redirect from homebrew/science to this tap?

Yes, there is, but the Homebrew maintainers decided not to do that due to security concerns, because Brewsci is maintained by different people than Homebrew. It is posted in the README.md of Homebrew/science now: https://github.com/Homebrew/homebrew-science#readme

**Comment by sjackman** [comment]
This migration process is well under way, and this checklist is no longer up to date. Closing this tracking issue, as it's no longer useful.
